version: '3.8'

services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '4000:5432'
