spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?user=${DB_USER}&password=${DB_PASSWORD}
    hikari:
      pool-name: book-market
      maximum-pool-size: 160
      minimum-idle: 50
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 10000
      jackson:
        property-naming-strategy: SNAKE_CASE

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, metrics
        exclude: "env,beans"
    info:
      enabled: true

server:
  error:
    include-message: always
  servlet:
    context-path: /api/book-market
  tomcat:
    threads:
      max: 160