spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:4000/postgres?user=postgres&password=postgres
    hikari:
      pool-name: book-market
      maximum-pool-size: 160
      minimum-idle: 50
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 10000
      jackson:
        property-naming-strategy: SNAKE_CASE